In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
cd Downloads

C:\Users\18329\Downloads


In [3]:
df= pd.read_excel('extract.xlsx')

In [4]:
df.head()

YEAR  SERIAL  STRATA  PSU     NHISHID  HHWEIGHT  PERNUM         NHISPID  \
0  2010       1    6001    2  2010000001    3042.0       1  20100000010101   
1  2010       1    6001    2  2010000001    3042.0       2  20100000010102   
2  2010       1    6001    2  2010000001    3042.0       3  20100000010103   
3  2010       2    6249    2  2010000002    1124.0       1  20100000020101   
4  2010       2    6249    2  2010000002    1124.0       2  20100000020102   

  HHX  FMX  ...  CSTATFLG  AGE  SEX  RACEA  HISPETH  EDUC  INCFAM97ON2    BMI  \
0   1  1.0  ...         0   43    2    100       30   502         32.0  18.24   
1   1  1.0  ...         0   42    1    100       30   502         32.0   0.00   
2   1  1.0  ...         1   11    2    100       30   108         32.0   0.00   
3   2  1.0  ...         0   24    2    100       20   201         20.0   0.00   
4   2  1.0  ...         0   27    2    100       20   201         20.0   0.00   

   BWGTGRAM  USUALPL  
0       0.0        2  
1       0.0        0  
2    2410.0        2  
3       0.0        0  
4       0.0        0  

[5 rows x 27 columns]

In [5]:
df.columns

Index(['YEAR', 'SERIAL', 'STRATA', 'PSU', 'NHISHID', 'HHWEIGHT', 'PERNUM',
       'NHISPID', 'HHX', 'FMX', 'PX', 'PERWEIGHT', 'SAMPWEIGHT', 'LONGWEIGHT',
       'PARTWEIGHT', 'FWEIGHT', 'ASTATFLG', 'CSTATFLG', 'AGE', 'SEX', 'RACEA',
       'HISPETH', 'EDUC', 'INCFAM97ON2', 'BMI', 'BWGTGRAM', 'USUALPL'],
      dtype='object')

In [6]:
df= df.drop(columns=['YEAR','SERIAL','PSU','NHISHID','HHWEIGHT','PERNUM','NHISPID','FMX','PX','PERWEIGHT','LONGWEIGHT','PARTWEIGHT','FWEIGHT','ASTATFLG','CSTATFLG','HISPETH','STRATA','HHX'])

In [7]:
df.head()

SAMPWEIGHT  AGE  SEX  RACEA  EDUC  INCFAM97ON2    BMI  BWGTGRAM  USUALPL
0      6011.0   43    2    100   502         32.0  18.24       0.0        2
1         0.0   42    1    100   502         32.0   0.00       0.0        0
2      2895.0   11    2    100   108         32.0   0.00    2410.0        2
3         0.0   24    2    100   201         20.0   0.00       0.0        0
4         0.0   27    2    100   201         20.0   0.00       0.0        0

In [8]:
df= df[df['BWGTGRAM'] != 0]


In [9]:
df.head()

SAMPWEIGHT  AGE  SEX  RACEA  EDUC  INCFAM97ON2  BMI  BWGTGRAM  USUALPL
2       2895.0   11    2    100   108         32.0  0.0    2410.0        2
8       8702.0   17    2    100   115         20.0  0.0    2580.0        2
13      6537.0   14    1    100   110         32.0  0.0    4366.0        2
34      7910.0    4    2    100     0         32.0  0.0    4083.0        2
44      3864.0    8    2    434   105         32.0  0.0    4225.0        2

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 182702 entries, 2 to 947023
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   SAMPWEIGHT   182702 non-null  float64
 1   AGE          182702 non-null  int64  
 2   SEX          182702 non-null  int64  
 3   RACEA        182702 non-null  int64  
 4   EDUC         182702 non-null  int64  
 5   INCFAM97ON2  104154 non-null  float64
 6   BMI          104154 non-null  float64
 7   BWGTGRAM     104154 non-null  float64
 8   USUALPL      182702 non-null  int64  
dtypes: float64(4), int64(5)
memory usage: 13.9 MB


In [11]:
#df=df.drop(('HHX'), axis=1)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 182702 entries, 2 to 947023
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   SAMPWEIGHT   182702 non-null  float64
 1   AGE          182702 non-null  int64  
 2   SEX          182702 non-null  int64  
 3   RACEA        182702 non-null  int64  
 4   EDUC         182702 non-null  int64  
 5   INCFAM97ON2  104154 non-null  float64
 6   BMI          104154 non-null  float64
 7   BWGTGRAM     104154 non-null  float64
 8   USUALPL      182702 non-null  int64  
dtypes: float64(4), int64(5)
memory usage: 13.9 MB


In [13]:
df.describe()

SAMPWEIGHT            AGE            SEX          RACEA  \
count  182702.000000  182702.000000  182702.000000  182702.000000   
mean     7184.103409      24.820369       1.504242     166.373838   
std      5999.217261      36.814054       0.502680     162.141621   
min        63.000000       0.000000       1.000000     100.000000   
25%      3353.000000       7.000000       1.000000     100.000000   
50%      5607.710000      14.000000       2.000000     100.000000   
75%      9151.573250      39.000000       2.000000     200.000000   
max    122902.920000     999.000000       9.000000     990.000000   

                EDUC    INCFAM97ON2       BMI       BWGTGRAM        USUALPL  
count  182702.000000  104154.000000  104154.0  104154.000000  182702.000000  
mean      156.648537      26.324356       0.0    3921.337260       1.971270  
std       151.867992      21.386971       0.0    2054.327135       0.406677  
min         0.000000      10.000000       0.0     500.000000       1.000000  
25%       102.000000      10.000000       0.0    2977.000000       2.000000  
50%       109.000000      20.000000       0.0    3374.000000       2.000000  
75%       201.000000      32.000000       0.0    3799.000000       2.000000  
max       999.000000      99.000000       0.0    9999.000000       9.000000

In [14]:
df.RACEA.unique()

array([100, 434, 200, 412, 310, 416, 600, 411, 580, 590, 400, 980, 350,
       300, 990, 970], dtype=int64)

In [15]:
df['RACEA'].replace({100:'White',434:'Other',200:'Black',412:'Pacific Islander',
310:'American Indian',416:'Asian Indian',600:'Multiple Race',411:'Chinese',
580:'Other',590:'Other',400:'Asian',980:'Unknown', 350:'Alaskan Native',300:'Aluet',
990:'Unkown',970:'Refused'}, inplace=True)

In [16]:
df.EDUC.unique()

array([108, 115, 110,   0, 105, 102, 107, 106, 114, 113, 111, 109, 104,
       116, 997, 201, 998, 999, 202, 301, 400, 303, 501, 503, 103, 302,
       502], dtype=int64)

In [17]:
df['EDUC'].replace({108:'fifth Grade',115:'Eleven Grade',110:'Seven Grade',
0:'No School',105:'Second Grade',102:'Kindergaden',107:'Fourth Grade',106:'Third Grade',
114:'Ten Grade',113:'Nine Grade',111:'Eight Grade',109:'six Grade',104:'First Grade',
116:'Twelve No Diploma',997:'Unkown',999:'Unknown',202:'GED',301:'College No D',
400:'Bachelors',303:'Acedemic Program',503:'PHD EdD',501:'Master',103:'Grade one-eleven',
302:'Technical',502:'MD DDS DVM'}, inplace=True)

In [26]:
df.head()

SAMPWEIGHT  AGE     SEX  RACEA          EDUC INCFAM97ON2  BMI  BWGTGRAM  \
2       2895.0   11  Female  White   fifth Grade    100000.0  0.0    2410.0   
8       8702.0   17  Female  White  Eleven Grade     74999.0  0.0    2580.0   
13      6537.0   14    Male  White   Seven Grade    100000.0  0.0    4366.0   
34      7910.0    4  Female  White     No School    100000.0  0.0    4083.0   
44      3864.0    8  Female  Other  Second Grade    100000.0  0.0    4225.0   

     USUALPL  
2   PreNatal  
8   PreNatal  
13  PreNatal  
34  PreNatal  
44  PreNatal

In [19]:
df.SEX.unique()

array([2, 1, 7, 9], dtype=int64)

In [20]:
df['SEX'].replace({2:'Female',1:'Male',7:'Unkown'}, inplace=True)

In [21]:
df.INCFAM97ON2.unique()

array([32., 20., 10., 31., 98., 99., nan])

In [22]:
df['INCFAM97ON2'].replace({32.0:100000,20.0:74999,10.0:34999,31:99999,
98.0:'Unkown',99.0:'Unkown'}, inplace=True)

In [23]:
#df['INCFAM97ON2']= 'Income'

In [24]:
df.USUALPL.unique()

array([2, 1, 3, 9, 7, 8], dtype=int64)

In [25]:
df['USUALPL'].replace({2:'PreNatal',1:'No', 3:'More Place',9:'Unkown',7:'Unkown',8:'Unkown'}, inplace=True)

In [27]:
df= df.rename(columns={'USUALPL':'Medicare','INCFAM97ON2':'Income'})

In [28]:
df.head()

SAMPWEIGHT  AGE     SEX  RACEA          EDUC    Income  BMI  BWGTGRAM  \
2       2895.0   11  Female  White   fifth Grade  100000.0  0.0    2410.0   
8       8702.0   17  Female  White  Eleven Grade   74999.0  0.0    2580.0   
13      6537.0   14    Male  White   Seven Grade  100000.0  0.0    4366.0   
34      7910.0    4  Female  White     No School  100000.0  0.0    4083.0   
44      3864.0    8  Female  Other  Second Grade  100000.0  0.0    4225.0   

    Medicare  
2   PreNatal  
8   PreNatal  
13  PreNatal  
34  PreNatal  
44  PreNatal

In [29]:
df.reset_index()

index  SAMPWEIGHT  AGE     SEX  RACEA          EDUC    Income  BMI  \
0            2    2895.000   11  Female  White   fifth Grade  100000.0  0.0   
1            8    8702.000   17  Female  White  Eleven Grade   74999.0  0.0   
2           13    6537.000   14    Male  White   Seven Grade  100000.0  0.0   
3           34    7910.000    4  Female  White     No School  100000.0  0.0   
4           44    3864.000    8  Female  Other  Second Grade  100000.0  0.0   
...        ...         ...  ...     ...    ...           ...       ...  ...   
182697  947019   11654.981   17  Female  White     No School       NaN  NaN   
182698  947020    4880.044   76  Female  White   Kindergaden       NaN  NaN   
182699  947021   10955.338   71  Female  White     Technical       NaN  NaN   
182700  947022    6802.422   77    Male  White     Technical       NaN  NaN   
182701  947023   20578.937   70    Male  Black           201       NaN  NaN   

        BWGTGRAM  Medicare  
0         2410.0  PreNatal  
1         2580.0  PreNatal  
2         4366.0  PreNatal  
3         4083.0  PreNatal  
4         4225.0  PreNatal  
...          ...       ...  
182697       NaN  PreNatal  
182698       NaN  PreNatal  
182699       NaN  PreNatal  
182700       NaN  PreNatal  
182701       NaN  PreNatal  

[182702 rows x 10 columns]

In [30]:
df.head()

SAMPWEIGHT  AGE     SEX  RACEA          EDUC    Income  BMI  BWGTGRAM  \
2       2895.0   11  Female  White   fifth Grade  100000.0  0.0    2410.0   
8       8702.0   17  Female  White  Eleven Grade   74999.0  0.0    2580.0   
13      6537.0   14    Male  White   Seven Grade  100000.0  0.0    4366.0   
34      7910.0    4  Female  White     No School  100000.0  0.0    4083.0   
44      3864.0    8  Female  Other  Second Grade  100000.0  0.0    4225.0   

    Medicare  
2   PreNatal  
8   PreNatal  
13  PreNatal  
34  PreNatal  
44  PreNatal

In [31]:
df = df.replace('Unknown', np.nan)


In [39]:
df.isnull().sum()

SAMPWEIGHT    0
AGE           0
SEX           0
RACEA         0
EDUC          0
Income        0
BMI           0
BWGTGRAM      0
Medicare      0
dtype: int64

In [38]:
df.dropna(inplace=True)

In [45]:
df

SAMPWEIGHT  AGE     SEX  RACEA          EDUC    Income  BMI  BWGTGRAM  \
8           8702.0   17  Female  White  Eleven Grade   74999.0  0.0    2580.0   
121         1486.0   17    Male  White  Eleven Grade   34999.0  0.0    3005.0   
126         1406.0   16  Female  White     Ten Grade   74999.0  0.0    2438.0   
138         3539.0   16  Female  White    Nine Grade   34999.0  0.0    2212.0   
159         1274.0   16    Male  White   Eight Grade   74999.0  0.0    3402.0   
...            ...  ...     ...    ...           ...       ...  ...       ...   
868276     17224.0   16  Female  White    Nine Grade  100000.0  0.0    3431.0   
868293      6416.0   17    Male  White     Ten Grade  100000.0  0.0    3799.0   
868300      8137.0   17  Female  White  Eleven Grade  100000.0  0.0    3998.0   
868355      4408.0   16  Female  Black     Ten Grade   99999.0  0.0    3714.0   
868454      5049.0   17  Female  White  Eleven Grade  100000.0  0.0    9999.0   

        Medicare  
8       PreNatal  
121     PreNatal  
126     PreNatal  
138     PreNatal  
159           No  
...          ...  
868276  PreNatal  
868293  PreNatal  
868300  PreNatal  
868355  PreNatal  
868454  PreNatal  

[13531 rows x 9 columns]

In [44]:
 df=df[df['AGE'] > 15]  


In [50]:
df.reset_index()

index  SAMPWEIGHT  AGE     SEX  RACEA          EDUC    Income  BMI  \
0           8      8702.0   17  Female  White  Eleven Grade   74999.0  0.0   
1         121      1486.0   17    Male  White  Eleven Grade   34999.0  0.0   
2         126      1406.0   16  Female  White     Ten Grade   74999.0  0.0   
3         138      3539.0   16  Female  White    Nine Grade   34999.0  0.0   
4         159      1274.0   16    Male  White   Eight Grade   74999.0  0.0   
...       ...         ...  ...     ...    ...           ...       ...  ...   
13526  868276     17224.0   16  Female  White    Nine Grade  100000.0  0.0   
13527  868293      6416.0   17    Male  White     Ten Grade  100000.0  0.0   
13528  868300      8137.0   17  Female  White  Eleven Grade  100000.0  0.0   
13529  868355      4408.0   16  Female  Black     Ten Grade   99999.0  0.0   
13530  868454      5049.0   17  Female  White  Eleven Grade  100000.0  0.0   

       BWGTGRAM  Medicare  
0        2580.0  PreNatal  
1        3005.0  PreNatal  
2        2438.0  PreNatal  
3        2212.0  PreNatal  
4        3402.0        No  
...         ...       ...  
13526    3431.0  PreNatal  
13527    3799.0  PreNatal  
13528    3998.0  PreNatal  
13529    3714.0  PreNatal  
13530    9999.0  PreNatal  

[13531 rows x 10 columns]

In [54]:
df.to_excel('dfclean.xlsx', index=None)